In [1]:
import numpy as np

In [2]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7])

In [3]:
type(numbers)

numpy.ndarray

Это означает, что переменная numbers является объектом класса numpy.ndarray, который представляет собой многомерный массив, предоставляемый библиотекой NumPy. Этот тип данных специально разработан для работы с массивами чисел и поддерживает различные математические операции и методы, которые делают его более мощным и эффективным по сравнению с обычными списками Python.

In [4]:
numbers.std()

2.0

In [5]:
numbers.mean()

4.0

Метод `cumsum()` в `NumPy` используется для вычисления кумулятивной суммы элементов массива. Это означает, что метод возвращает новый массив, в котором каждый элемент является суммой всех предыдущих элементов исходного массива, включая текущий элемент.

In [6]:
numbers.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [7]:
A = [[1, 4, 6], # row 1
     [4, 6, 7]] # row 2
A

[[1, 4, 6], [4, 6, 7]]

In [8]:
type(A) # list

list

In [11]:
A_arr = np.array(A) # array
A_arr

array([[1, 4, 6],
       [4, 6, 7]])

In [12]:
np.shape(A)

# (2, 3) --> 2 rows, 3 columns

(2, 3)

In [14]:
# random matrix

B = np.random.rand(3, 3)
B

array([[0.23646617, 0.76751337, 0.93849228],
       [0.34499675, 0.69483261, 0.88882917],
       [0.58675409, 0.67108054, 0.64058551]])

In [16]:
# если число столбцов двух матриц одинаково, то можно перемножать

C = np.matmul(A, B)
C

array([[ 5.13697775,  7.57332704,  8.33732206],
       [ 7.12312385, 11.9366129 , 13.57104277]])

In [17]:
C.shape

(2, 3)

### Сингулярное разложение (SVD, Singular Value Decomposition)

Команда `u, s, vh = np.linalg.svd(C)` выполняет сингулярное разложение (SVD, Singular Value Decomposition) матрицы C. Сингулярное разложение — это факторизация матрицы, которая разлагает матрицу на три других матрицы.

Это одна из ключевых операций в линейной алгебре, особенно полезная в задачах понижения размерности, обработки изображений, машинного обучения и других областях.

In [ ]:
# linear algebra

u, s, vh = np.linalg.svd(C)

### Применение: SVD широко используется в:

* Понижении размерности данных, например, в методе главных компонент (PCA).
* Обработке изображений для сжатия данных.
Решении систем линейных уравнений и псевдообратной матрицы.
* Удалении шума из данных и других задачах анализа данных.